<li item="{\'path\':\'{filePath}\'}" onmouseover="this.style[\'background-color\']=\'silver\'" onmouseout="this.style[\'background-color\']=\'white\'">\
	<table style="width:100%;cursor:pointer;font-size:12px;font-weight:600;color:steelblue;" border="0" onselect="return false">\
		<tr>\
			<td rowspan="4" style="width:90px;text-align:center">\
				<img src="{imgSrc}" style="" title="{capColor}">\
			</td>\
			<td>\
				ФИО:\
			</td>\
			<td title="ФИО">\
				{FIO}\
			</td>\
		</tr>\
		<tr>\
			<td>\
				Дата регистрации:\
			</td>\
			<td title="Дата регистрации">\
				{date}\
			</td>\
		</tr>\
		<tr>\
			<td>\
				Skype:\
			</td>\
			<td title="Skype">\
				{skype}\
			</td>\
		</tr>\
		<tr>\
			<td>\
				E-mail:\
			</td>\
			<td title="Электронная почта">\
				{email}\
			</td>\
		</tr>\
	</table>\
</li>